config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    collection do
      Task.statuses.keys.each do |status|
        get status
      end
      get :canceled
    end
    get :retry
    member do
      post :cancel
    end
  end
  resources :workers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/new_task", to: "tasks#new_task_for_worker"
  get "/tasks_canceled", to: "tasks#tasks_canceled"
  post "/update_task", to: "tasks#update_task"

  root to: 'tasks#index'
end

app/models/task.rb
class Task < ApplicationRecord
  validates_presence_of :config_json
  # validates_presence_of :status, :simulations_count, :eta, :config, :config_json, :benchmark_version,
  #                       :report_table, :report_distribution, :report_graph, :report_w1, :report_dragons, :progress,
  #                       :line_count, :bet_per_line, :currency, :threads

  enum status: [:todo, :in_progress, :done, :failed, :canceled]

  def report_s
    r = report&.gsub("\n", "<br/>")
    r = r&.gsub(" ", "&nbsp;")
    r
  end

  def outdated?
    self.progress && ( Time.now - (self.updated_at || Time.unix(0)) > 1.hour )
  end

  def created_at_s
    created_at.strftime("%H:%M, %B %e")
  end

  def updated_at_s
    updated_at.strftime("%H:%M, %B %e")
  end

  def changed_at
    self.updated_at || Time.unix(0)
  end

  def changed_today?
    changed_at > Time.now - 1.day
  end

  def changed_yesterday?
    (changed_at < Time.now - 1.day) && (changed_at > Time.now - 2.day)
  end

  def changed_this_week?
    (changed_at < Time.now - 2.day) && (changed_at > Time.now - 7.day)
  end

  def changed_ago?
    (changed_at < Time.now - 7.day)
  end

  def simulations_s
    case self.simulations_count
    when 5000
      "100K"
    when 50000
      "1M"
    when 500000
      "10M"
    when 5000000
      "100M"
    end
  end

  def eta_s
    span = Time.at(self.eta.to_i).utc
    "#{span.hour}h #{span.min}m #{span.sec}s"
  end

  def report_available?
    (self.done? || self.failed?) && self.report
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:new_task_for_worker, :update_task, :tasks_canceled]
  skip_before_action :verify_authenticity_token, only: [:new_task_for_worker, :update_task, :tasks_canceled]


  Task.statuses.keys.each do |status|
    define_method status do
      @tasks = Task.all
      @tasks_scoped = Task.send(status).order(updated_at: :desc)
      render :tasks
    end
  end

  def index
    redirect_to :todo_tasks
  end

  def canceled
    @tasks = Task.all
    @tasks_scoped = Task.canceled.order(updated_at: :desc)
    if @tasks_scoped.size.positive?
      render :tasks
    else
      redirect_to :failed_tasks
    end
  end

  def tasks_canceled
    with_token do
      @tasks = Task.all
      @tasks_scoped = Task.canceled.order(updated_at: :desc)
      render json: Task.canceled.ids.to_json
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new({
        benchmark_version: "",
        status: :todo,
        report_table: true,
        report_distribution: true,
        threads: 20
    })
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_task_for_worker
    if validate_token
      response.content_type = "application/json"
      worker = Worker.find_by(name: pick_params[:worker])
      if worker.nil?
        worker = Worker.create!(worker_params)
      else
        worker.touch
        worker.update(worker_version: pick_params[:worker_version], engine_version: pick_params[:engine_version])
        if worker.blocked
          render json: "null"
          return
        end
      end
      tasks = Task.where("(worker_id IS NULL OR worker_id = #{worker.id}) AND status = 0").limit("1")
      if tasks.length > 0
        task = tasks.first
        task.update!(worker_id: (worker.id || 0))
        task.update!(benchmark_version: (worker.worker_version || ""))
        task.update!(engine_version: (worker.engine_version || ""))
        task.save
        render json: task.to_json
      else
        worker.update(busy: false)
        render json: "null"
      end
    else
      render json: { error: "Token invalid" }.to_json
    end
  end

  def prevent_progress_on_canceled(task, update_params)
    !(task.canceled? && update_params[:status] != Task.statuses[:failed])
  end

  def update_task
    if validate_token
      task = Task.find(update_params[:id])
      worker = Worker.find_by(id: task.worker_id)
      worker.try(:touch)
      worker.update(busy: true)
      puts task
      task && prevent_progress_on_canceled(task, update_params) && task.update!(update_params)
      render json: task.to_json
    else
        render json: { error: "Forbidden" }
    end
  end

  def retry
    new_task = Task.find(params[:task_id]).dup
    new_task.created_at = Time.now
    new_task.updated_at = Time.now
    new_task.id = nil
    new_task.status = 0
    new_task.worker_id = nil
    if new_task.save
      redirect_to action: :index
    else
      flash[:danger] = "Could not create Task!"
      render :new
    end
  end

  def cancel
    set_task
    @task.canceled!
    redirect_to :canceled_tasks
  end

  private

  def with_token &block
    if validate_token
      yield
    else
      render json: { error: "Token invalid" }.to_json
    end
  end

  def validate_token
    params.permit(:token, :worker) && params.has_key?(:token) && params[:token] == "booming-games"
  end

  def update_params
    params.require(:task).permit(:id, :progress, :status, :report, :eta, :token, :task)
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def pick_params
      params.permit(:worker, :token, :worker_version, :engine_version)
    end

    def worker_params
      {
          name: pick_params[:worker],
          worker_version: pick_params[:worker_version],
          engine_version: pick_params[:engine_version]
      }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:status, :simulations_count, :eta, :report, :config, :config_json, :config_validation, :benchmark_version, :report_table, :report_distribution, :report_graph, :report_w1, :report_dragons, :progress, :line_count, :bet_per_line, :currency, :worker_id, :threads)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_checkbox(task, field)
    content_tag :div, class: "custom-control custom-switch" do
      concat(
          check_box("task[#{field}]", field, checked: task.send(field), class: 'custom-control-input', id: field.to_s) +
          label_tag(field, nil, class: 'custom-control-label', for: field.to_s)
      )
    end
  end

end

app/views/tasks/_form.slim
- if task.errors.any?
  div id="error_explanation"
    h2
      = pluralize(task.errors.count, "error")
    ul>
      - task.errors.full_messages.each do |message|
        li
          = message

== form_with(model: task, local: true) do |form|
  .row
    .col
      .form-group
        label Task name
        == text_field(:task, :config, value: task.config, placeholder: "Config name", class: "form-control", required: true)
      .form-group
        label Simulations count
        select.custom-select name="task[simulations_count]"
          option value="5000" 100K
          option value="50000" selected=true 1M
          option value="500000" 10M
          option value="5000000" 100M
      .form-group
        label Config JSON
        == text_area(:task, :config_json, value: task.config_json, placeholder: "JSON config content", class: "form-control", size: "30x10", required: true)

    .col
      - %i|report_table report_distribution report_graph report_w1 report_dragons config_validation|.each do |field|
        .form-group
          == task_checkbox(task, field)
      .form-group
        == text_field(:task, "line_count", value: task.line_count, placeholder: "Line count", class: "form-control", required: "required")
      .form-group
        == text_field(:task, "bet_per_line", value: task.bet_per_line, placeholder: "Bet per line", class: "form-control", required: "required")
      .form-group
        == text_field(:task, "currency", value: (task.currency || "EUR"), placeholder: "Currency", class: "form-control", required: "required")
  .float-right
    == submit_tag("Submit", class: "btn btn-success btn-lg")
    == link_to("Back", "/tasks", class: "btn btn-light btn-lg")

app/views/tasks/_show.slim
br
.card
  .card-body
    .row
      .col-md-5
        h5.card-title
          == link_to task.config, task_path(task)
          '
          - if task.todo?
            span class="badge badge-info" TODO
          - if task.in_progress?
            span class="badge badge-warning" RUNNING, ETA: #{task.eta_s}
          - if task.failed?
            span class="badge badge-danger" FAILED
          - if task.done?
            span class="badge badge-success" DONE

        h5.card-subtitle.mb-2.text-muted == task.simulations_s
        div.card-text
          strong Reports:
          ul
            - if task.report_table
              li Table
            - if task.report_distribution
              li Distribution
            - if task.report_w1
              li W1
            - if task.report_dragons
              li Dragons

      .col-md-4
        div
          strong Run options:
        ul
          li
            strong Currency:
            '
            = task.currency
            li
              strong Bet per line:
              '
              = task.bet_per_line
            li
              strong Lines:
              '
              = task.line_count
            li
              strong Threads:
              '
              = task.threads
            li
              strong Validate config:
              '
              = task.config_validation

      .col-md-3
        div
          strong Created at
          ':
          span #{task.created_at_s}
        div
          strong Updated at
          ':
          span #{task.updated_at_s}
        div
          strong Worker
          ':
          span #{task.worker_id}
        div
          strong Benchmark Version
          ':
          span #{task.benchmark_version}
        div
          strong Engine Version
          ':
          span #{task.engine_version}
        - if task.todo?
          == link_to("Edit", edit_task_path(task), class: "btn btn-success btn-block")
        br
        - if task.done? || task.outdated? || task.failed?
          == link_to("Delete", task_path(task), "data-method": "delete", "data-confirm": "Are you sure?", class: "btn btn-danger btn-block")

        br
        - if task.in_progress?
          == link_to("Cancel", cancel_task_path(task), "data-method": "post", "data-confirm": "Are you sure?", class: "btn btn-danger btn-block")

        br
        - if task.report_available?
          a class="btn btn-primary btn-block" data-toggle="collapse" href="#report-#{task.id}" role="button" aria-expanded="false" aria-controls="report-#{task.id}" View report
        br
        - if task.done? || task.outdated? || task.failed?
          == link_to("Retry", task_retry_path(task), class: "btn btn-primary btn-block")

  - if task.in_progress? || task.canceled?
    div class="progress"
      div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow=task.progress aria-valuemin="0" aria-valuemax="100" style="width: #{task.progress}%" ETA #{task.eta_s}

  - if task.report_available?
    .collapse id="report-#{task.id}" class="#{"show" if show_report}"
      .jumbotron style="font-family: monospace"
        == task.report_s

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.slim
p id="notice"
  = notice

.row
  .col-sm-11
    h2 Tasks
  .col-sm-1
    a.btn.btn-success.btn-sm href="/tasks/new" New

ul#myTab.nav.nav-tabs role="tablist"
  li.nav-item
    a#home-tab.nav-link.active data-toggle="tab" href="#home" aria-controls="todo" tole="tab"
      span ToDo
      .badge.badge-secondary
        == @tasks.count{|t| t.todo?}
  li.nav-item
    a#inprogress-tab.nav-link data-toggle="tab" href="#inprogress" aria-controls="inprogress" role="tab"
      span In Progress
      .badge.badge-warning
        == @tasks.count{|t| t.in_progress?}
  li.nav-item
    a#canceled-tab.nav-link data-toggle="tab" href="#canceled" aria-controls="canceled" role="tab"
      span Canceled
      .badge.badge-warning
        == @tasks.count { |t| t.canceled? }
  li.nav-item
    a#done-tab.nav-link data-toggle="tab" href="#done" aria-controls="done" role="tab"
      span Done
      .badge.badge-success
        == @tasks.count{|t| t.done?}
  li.nav-item
    a#failed-tab.nav-link data-toggle="tab" href="#failed" aria-controls="failed" role="tab"
      span Failed
      .badge.badge-danger
        == @tasks.count{|t| t.failed?}

#myTabContent.tab-content
  #home.tab-pane.show.active
    - @tasks_todo.each do |task|
      == render(partial: "show", locals: { task: task, show_report: false })

  #canceled.tab-pane.fade
    - @tasks_canceled.each do |task|
      == render(partial: "show", locals: {task: task, show_report: false})

  #inprogress.tab-pane.fade
    - @tasks_progress.each do |task|
      == render(partial: "show", locals: { task: task, show_report: false  })

  #done.tab-pane
    - unless @done_today.size.zero?
      .h2 Today
    - @done_today.each do |task|
      == render(partial: "show", locals: { task: task, show_report: false  })
      hr
    - unless @done_yesterday.size.zero?
      .h2 Yesterday
    - @done_yesterday.each do |task|
      == render(partial: "show", locals: { task: task, show_report: false  })
      hr
    - unless @done_this_week.size.zero?
      .h2 This week
    - @done_this_week.each do |task|
      == render(partial: "show", locals: { task: task, show_report: false  })
      hr
    - unless @done_ago.size.zero?
      .h2 Long time ago
    - @done_ago.each do |task|
      == render(partial: "show", locals: { task: task, show_report: false  })
      hr

  #failed.tab-pane
    - @tasks_failed.each do |task|
      == render(partial: "show", locals: { task: task, show_report: false  })

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<%= render partial: 'tasks/show', locals: { task: @task, show_report: true } %>

app/views/tasks/tasks.slim
p id="notice"
  = notice

.row
  .col-sm-11
    h2 Tasks
  .col-sm-1
    a.btn.btn-success.btn-sm href="/tasks/new" New

ul#myTab.nav.nav-tabs role="tablist"
  li.nav-item
    a#home-tab.nav-link href="/tasks/todo" class="#{'active' if action_name == 'todo'}"
      span ToDo
      .badge.badge-secondary
        == @tasks.todo.count
  li.nav-item
    a#inprogress-tab.nav-link href="/tasks/in_progress" class="#{'active' if action_name == 'in_progress'}"
      span In Progress
      .badge.badge-warning
        == @tasks.in_progress.count
  - if @tasks.canceled.count.positive?
    li.nav-item
      a#canceled-tab.nav-link href="/tasks/canceled" class="#{'active' if action_name == 'canceled'}"
        span Canceled
        .badge.badge-warning
          == @tasks.canceled.count
  li.nav-item
    a#done-tab.nav-link href="/tasks/done" class="#{'active' if action_name == 'done'}"
      span Done
      .badge.badge-success
        == @tasks.done.count
  li.nav-item
    a#failed-tab.nav-link href="/tasks/failed" class="#{'active' if action_name == 'failed'}"
      span Failed
      .badge.badge-danger
        == @tasks.failed.count

.tab-content
  - @tasks_scoped.each do |task|
    == render(partial: "show", locals: { task: task, show_report: false  })