config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    collection do
      Task.statuses.keys.each do |status|
        get status
      end
      get :canceled
    end
    get :retry
    member do
      post :cancel
    end
  end
  resources :workers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/new_task", to: "tasks#new_task_for_worker"
  get "/tasks_canceled", to: "tasks#tasks_canceled"
  post "/update_task", to: "tasks#update_task"

  root to: 'tasks#index'
end

app/models/worker.rb
class Worker < ApplicationRecord
  scope :recent, -> { where("updated_at > now() - '1 minute'::interval") }
  scope :not_blocked, -> { where("blocked != true") }

  scope :active, -> { recent.not_blocked }
  scope :busy,   -> { recent.not_blocked.where("busy == TRUE") }
  scope :available,   -> { recent.not_blocked.where("busy != TRUE") }

  def active?
    (Time.now - updated_at) < 1.minutes
  end

  def state
    if active?
       if busy
         "waiting"
       else
         "active"
       end
    else
      "dead"
    end
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all.order(updated_at: :desc)
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:blocked)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_with(model: worker, local: true) do |form| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
        <% worker.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :blocked %>
    <%= form.check_box :blocked %>
  </div>

  <div class="actions">
    <%= form.submit "Update", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Benchmark Version</th>
      <th>Engine Version</th>
      <th>Activity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr class="<%= worker.state %>">
        <td>
          <%= worker.id %>
          -
          <%= worker.name %>
          <%- if worker.blocked %>
            <span class="badge badge-danger">BLOCKED</span>
          <% end %>
          <%- if worker.busy %>
            <span class="badge badge-warning">BUSY</span>
          <% end %>
        </td>
        <td><%= worker.worker_version %></td>
        <td><%= worker.engine_version %></td>
        <td><%= time_ago_in_words worker.updated_at %> ago</td>
        <td>
          <%= link_to 'Edit', edit_worker_path(worker), class: 'btn btn-warning' %>
          <% unless worker.active? %>
            <%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @worker.name %>
</p>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>