config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    collection do
      Task.statuses.keys.each do |status|
        get status
      end
      get :canceled
    end
    get :retry
    member do
      post :cancel
    end
  end
  resources :workers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/new_task", to: "tasks#new_task_for_worker"
  get "/tasks_canceled", to: "tasks#tasks_canceled"
  post "/update_task", to: "tasks#update_task"

  root to: 'tasks#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :load_workers_data

  def load_workers_data
    @free_workers = Worker.available.count
    @active_workers = Worker.active.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Simulations manager", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Tasks', tasks_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Workers #{@free_workers} / #{@active_workers}", workers_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>

</nav>